[package]
name = "renderer"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
# futures = "0.3.5"
thiserror = "1.0.20"
wgpu = "0.6.0"
winit = "0.22.2"
