[package]
name = "renderer"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0.20"
wad = { path = "../wad" }
wgpu = "0.6.0"
winit = "0.22.2"
