[package]
name = "ferrodoom"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]
edition = "2018"

[dependencies]
async-std = "1.6.3"
renderer = { path = "../renderer" }
wad = { path = "../wad" }
winit = "0.22.2"
